export const BUDGET_TYPES = {
  FOOD: 'FOOD',
  EMERGENCY_FUND: 'EMERGENCY_FUND',
  DAILY_BUDGET: 'DAILY_BUDGET',
  HYGIENE: 'HYGIENE',
  BUFFER_BUDGET: 'BUFFER_BUDGET',
  HOME_CONTRIBUTION: 'HOME_CONTRIBUTION',
  TUITION_CONTRIBUTION: 'TUITION_CONTRIBUTION',
  SAVINGS: 'SAVINGS',
  INVESTMENTS: 'INVESTMENTS',
  TRANSPORTATION: 'TRANSPORTATION',
  SELF: 'SELF',
  TECH: 'TECH',
};
