name: afterTaxes Database Backup
on:
  push:
    branches: [monorepo]
  schedule:
    - cron: '0 22 * * 0'

jobs:
  backup:
    name: 'Backup Database'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depedendencies
        run: cd backup && yarn install --frozen-lockfile
        run: cd db_backup && yarn install --frozen-lockfile
      - name: Backup aftertaxes database
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: cd backup && yarn start
