name: afterTaxes CI
on:
  push:
    branches: [github-actions]
jobs:
  tests:
    name: 'Unit and integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Run Test
        env:
          API_PATH: /api/v1
        run: npm t
