name: afterTaxes CI
on:
  push:
    branches: [github-actions]
jobs:
  tests:
    name: 'Perform unit and integration tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
