name: Build and deploy afterTaxes apps

on:
  push:
    branches: [production, prod-test]

jobs:
  server-deploy:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Build, Push and Release a Docker container to Heroku.
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: aftertaxes
        dockerfile_directory: ./
        dockerfile_name: Dockerfile.heroku
        docker_options: '--no-cache'
        process_type: web

  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install --frozen-lockfile

        # For deployment, the build scope will only include the web directory and
        # the commons directory if there is
      - name: Build application
        run: yarn build:web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'packages/web/build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
